ansible_become_pass: ENC[AES256_GCM,data:GTAlOzYIjMgVTbhn,iv:AExR6iK0NAdXN2T/+Fs8qDHdjEk49j7UW6FfYPeeDww=,tag:QDwLtTBllbUn+mCJZ2K8Lw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age145m3eq5cu4nhh3kxmktanvazv7m05ghprvtcpde02m5zwzrclenqnyq7sz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbjlsVU4xMDk0ZElZN053
            NGp2Z25iUC9Oek9CYk90UTJZMk1oSVluMFJZClkwSklJSElPclEybHRrcmVOL1Uw
            Z09ubXhLMk93VHBDVHZzUUljNm52emcKLS0tIGVDRXVKczcvc0JSdGtPTlZYd0N6
            L21Id0FUeWxiTG9BcTZ4TXorVGN5dlkKsaQuK1FAZ1N8wnOE9tWl+9q4B4NaNzi8
            Fo0EH6bMt87U7AcjnIryU8LJV8p36ksBTkhPw8unXGTu889OR2cvfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-09T12:28:35Z"
    mac: ENC[AES256_GCM,data:kpayWlowPOrG4f8LHaNiLeotPKnehcvwthZIVwczfLIDPx+SnTE6pGitkkXkN3US7g3QsC8br2h3+e10/13vtVuuNHTgE8nCbNSoza9p9L/epEGNTtgDzKokS8ivOnqqnyyRLYxejE+3sPsqz00h5wH5iAoZ+RyPUOzOXjJFmpc=,iv:S1BJCDVHOOYBDwJHWiP44ODnO5VIoAOu4bAQ5Tn8xtI=,tag:azo9aoymwDLOt+dq/r1ODQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
