ansible_become_pass: ENC[AES256_GCM,data:RsZ7f6qdpVGbYPYT,iv:0qLPj0L7Zyh1eEDQbMPzdsA+GA7IChQhO/b6pmED3Yw=,tag:tX1wnTT4/asmdLckVPhhFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age145m3eq5cu4nhh3kxmktanvazv7m05ghprvtcpde02m5zwzrclenqnyq7sz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsS3hST1RDbWVqOFVjYWg1
            eUpaemlDVHBZNk4rSzFZK1dsVURlRnplS1YwCkpSb0NCVXpnd3YwdUNwdkhVV1l3
            cHVFajg1UWszUkcwVUhXbEdxNWVaekUKLS0tIDRNWEhuZ0lOenFLMi9SNnF3TmFY
            cVhIZkU5VzBBeEJUdEVUWkdoS283L2sKWHgYnTVOngU7iGpSk7qAYaT27AcKXn/3
            aeHZwsvWHzO8/e5mT0Y8LMdBn1uuY4zecCx+RTPTjM0VUZvlkdeVgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-09T12:28:35Z"
    mac: ENC[AES256_GCM,data:1T13OqXbVBYDEPvZ1Va9HzC0wFs8QXT4vOXJ8/D/QqVPYjc4fOE93IkOLE7ticZTRrWDuJRZEEWzuCpKvz4RPfhRCDmMvQWZjNjhGQxFfSKxwGCAqnsUA87eY5W69e0/7IyP+mCJMHj4VDxpk0fy621QXt3UNjyBmpDpxzvz0Vs=,iv:9NqgUp5WMX9QIHkG++fMOZlAmsX1TSQnvEM6l9gzIlo=,tag:v12MkuMY8YJKiPNP2/bA4w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
