apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age145m3eq5cu4nhh3kxmktanvazv7m05ghprvtcpde02m5zwzrclenqnyq7sz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SytkOFUwamY2aXNRWEht
            MWppS2hJR0piR3lkNlprWVJLZmxYVkVnY2w4CjlpNjgxeEpWdTdVU21FWllySnZq
            UjZleWthbkxQUXlON3RONHVyejJlMGcKLS0tIGttMzdyeGl4aEx6VjJzMTNxc2U1
            OTQwc0pGYTJPWXRrdExFcFZQOUQwbDgKwELQ81cbj+nGwvSbaNoGIs2/L2qVP/QD
            vGDuI7D9ZTvGPlCPpv1u4VStEVyGDwHWuYw2EZcGVz3Vynd9ISbHTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-09T12:29:08Z"
    mac: ENC[AES256_GCM,data:Pl7GkTws1Z+hPiW6BJQI7QcaXFc1cfRuNeYfB7Y+EyquSvzZ9wJyitYeeL+XDsSbk+vQxbbuwYvxg40Lea335+AkoEGMVijGv/1pJIlzxbU06LCxyQlp3wnsJv5ZPJK6QSkbg9vB/5sUtVURgGq4FePkAGfQT8mgqNPagl6etiM=,iv:B9n5XxGRzCiBjLALKOPcIjMSajfmXGYzcos4og5znDY=,tag:p3N0PzgvUEcun6najSsMgw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
