apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:cvslcuFxpW2mVBvlZp+77Ai+K07tAZ8RWhmwxh1IlZvM1kWeWHjMVA==,iv:PlPBCtwJtYTFSim6E/4LNXY9eqc+zkQdngH9FTWH5bU=,tag:NeIidrChWtgBLFFeXP3lQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age145m3eq5cu4nhh3kxmktanvazv7m05ghprvtcpde02m5zwzrclenqnyq7sz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYnRsRWY3Y0FvRjFxTFZy
            R0RrZDRoaU1rS2ZTRjd6b3Z1MUsrVS8vVGpzClFnMStOTjQwRjJTNU5KVGZqeldJ
            bThEQ1cxeDFHb2xiNlpiLzNRTitabXMKLS0tIEN4RE4yZzg5aHpwWTZXdEpwNk5o
            Z1h0L0VVOEZIemNZTzNrRCswMHd3YWsK7VUcPYYBMrUxkzzo8BtXI0aeU7GlxhWv
            /DGIi8ZG2+4YgZVTXQ2i9gGdSj2G32+CQfmUvy35weLasnNn1rLfew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-09T11:50:19Z"
    mac: ENC[AES256_GCM,data:OGQdrRhT2/44PV9yZWy4elSHsRzNIojNWG5osE3DZGSPRkJ4/1TrprrXLsy/7dpWu2TLEN79gEWTgYHMQp0t9zjy7jaSpBx8lfOq1tZL55V1I63B3DqZ2DeaVxHxO+r0sQOkVIivnV5sc833trh6mwWQtnNxTss+9TNerAcg4Iw=,iv:fhIeaKvWQnurKpcFpkW22NAvWAFjPbyy1qcgSuoZTnw=,tag:+WLdzj5awLnl6feOnaCW1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
